syntax = "proto3";

package tech.qomet.agora.api.grpc.fin;

import "fin/identifier.proto";

option go_package = "qomet.tech/agora/daemons/gen-pkg/tech/qomet/agora/api/grpc/fin;agoraapigrpcfin";
option java_package = "tech.qomet.agora.api.grpc.fin";
option java_outer_classname = "AccountProto";
option csharp_namespace  = "Tech.Qomet.Agora.Api.Grpc.Fin";

enum AccountTypeEnum {
  ACCOUNT_TYPE_ENUM_UNKNOWN = 0;

  ACCOUNT_TYPE_ENUM_OMNIBUS = 1;
  ACCOUNT_TYPE_ENUM_SEGREGATED = 2;
  ACCOUNT_TYPE_ENUM_HOUSE = 3;
  ACCOUNT_TYPE_ENUM_CLIENT = 4;
  ACCOUNT_TYPE_ENUM_NOMINEE = 5;
  ACCOUNT_TYPE_ENUM_COLLATERAL = 6;
  ACCOUNT_TYPE_ENUM_ESCROW = 7;
  ACCOUNT_TYPE_ENUM_ISSUER = 8;
  ACCOUNT_TYPE_ENUM_CUSTODIAN = 9;
  ACCOUNT_TYPE_ENUM_CUSTODY = 10;

  ACCOUNT_TYPE_ENUM_OTHER = 0x0fff0000;
}

enum AccountStatusEnum {
  ACCOUNT_STATUS_ENUM_UNKNOWN = 0;

  ACCOUNT_STATUS_ENUM_ACTIVE = 1;
  ACCOUNT_STATUS_ENUM_INACTIVE = 2;
  ACCOUNT_STATUS_ENUM_SUSPENDED = 3;
  ACCOUNT_STATUS_ENUM_BLOCKED = 4;
  ACCOUNT_STATUS_ENUM_CLOSED = 5;
  ACCOUNT_STATUS_ENUM_PENDING = 6;
  ACCOUNT_STATUS_ENUM_TERMINATED = 7;
  ACCOUNT_STATUS_ENUM_ENABLED = 8;
  ACCOUNT_STATUS_ENUM_DISABLED = 9;

  ACCOUNT_STATUS_ENUM_OTHER = 0x0fff0000;
}

message Account {
  string iid = 1;                                                                          // REQUIRED: Internal identifier
  repeated FinIdentifier identifiers = 2;                                                  // OPTIONAL: Associated identifiers
  string external_account_id = 3;                                                          // OPTIONAL: External account identifier stored by participant

  AccountTypeEnum account_type = 4;                                                        // REQUIRED: Type of account
  AccountStatusEnum account_status = 8;                                                    // REQUIRED: Current account status

  map<string, string> display_names = 101;                                                 // OPTIONAL: Display names for localization
  map<string, string> descriptions = 102;                                                  // OPTIONAL: Descriptions for localization
  map<string, string> labels = 103;                                                        // OPTIONAL: Key-value labels
  repeated string tags = 104;                                                              // OPTIONAL: Tags for categorization
  map<string, string> metadata = 105;                                                      // OPTIONAL: Additional metadata
}

