syntax = "proto3";

package tech.qomet.agora.api.grpc.prtagent.v1;

option go_package = "qomet.tech/agora/daemons/gen-pkg/tech/qomet/agora/api/grpc/prtagent/v1;agoraapigrpcprtagentv1";
option java_package = "tech.qomet.agora.api.grpc.prtagent.v1";
option java_outer_classname = "Agent";
option csharp_namespace  = "Tech.Qomet.Agora.Api.Grpc.PrtAgent.V1";

service AgentService {
  rpc Ping(PingRequest) returns (PingResponse);
  rpc BiDirStreamPing(stream PingRequest) returns (stream PingResponse);
}

message PingRequest {
  string proposed_execution_id = 1;                                     // OPTIONAL: Client-proposed execution ID for tracking
  string string_to_be_ponged = 2;                                       // REQUIRED: Test string to be echoed back
}

message PingResponse {
  string ref_execution_id = 1;                                          // REQUIRED: Reference to the execution ID
  string pong_string = 2;                                               // REQUIRED: Echoed string from request
}